#!/bin/bash

unset -f rrev
unset -f init_env
unset -f rebuild

unset -v all_commits
unset -v start_commit
unset -v remove_list

declare start_commit=$1
shift 1
declare remove_list=$@

init_env ()
{

	declare -ga all_commits

	all_commits=( $(git log --format=%h $1..HEAD) )

	git clean -df; git reset --hard
	git checkout $1
}

rebuild ()
{
	for ((i=${#all_commits[@]}-1; i>=0; --i)); do
		echo -n "Proccessing $i: $(git log --oneline -1 ${all_commits[i]})..."

		git show -1 -p --full-index ${all_commits[i]} | git apply &> /dev/null
		git add . &> /dev/null
		git rm -rf --ignore-unmatch $remove_list --cached &> /dev/null
		git commit -a -C ${all_commits[i]} &> /dev/null
		if [[ $? -eq 0 ]]; then
			echo "Done."
		else
			echo
			echo "  Ignored."
		fi
	done
}

checkin ()
{
	git fetch ssh://review-opera.htc.com:29418/device/htc-jb +refs/heads/qct/jb-mr0-rel-qct8930aa+operaul:refs/remotes/opera/qct/jb-mr0-rel-qct8930aa+operaul
	git rebase opera/qct/jb-mr0-rel-qct8930aa+operaul
	git push ssh://review-opera.htc.com:29418/device/htc-jb HEAD:refs/heads/qct/jb-mr0-rel-qct8930aa+operaul
}

init_env $start_commit
rebuild
