#!/bin/bash

declare nlimit="$1"
shift 1
declare nobj=

for i in $(find . -type d -name *\\.git); do
	pushd . > /dev/null; cd $i;
	nobj=$(find objects | wc -l)
	if [[ "$nobj" -ge "$nlimit" ]]; then
		echo
		echo "## Project: $i"
		[[ "$@" != "" ]] && eval "$@" || echo "    $nobj."
	fi
	popd > /dev/null;
done
