#!/bin/bash

declare nlimit="$1"
shift 1
declare cmds="$*"
declare nobj=

for i in $(find . -type d -name *\\.git); do
	pushd . > /dev/null; cd $i;
	nobj=$(find objects | wc -l)
	if [ "$nobj" -ge "$nlimit" ]; then
		echo "## Project: $i"
		test "$cmds" != "" && eval "$cmds" || echo "    $nobj."
	fi
	popd > /dev/null;
done
