#!/bin/bash

declare br="$@"
declare proj=$(echo $(git config --local --get remote.origin.url) | sed 's/\(git\|ssh\):\/\/[^\/]*\(29419\)\?\///g')

if [ "$br" != "" ]; then
	for i in $br; do
		git push ssh://10.8.137.61:29419/$proj :$i
		git push ssh://mirror-ateam.htc.com:29419/$proj :$i
		git branch -Dr origin/$i
	done
else
	echo "no branch(s) specified"
fi
