#!/bin/bash
# CL=388966; Commit_id=b8a25ed49dfec3271230578d34797d149efc02ba; Name=jessica_yu@htc.com; Subject="Title: [T1] 1.only flash ""dzdata_XXX.img"" into dzdata 2.add userdata checksum on display"; 4 days ago
git --git-dir=.repo/manifests/.git/ log -1 --format="%s %cr" -- $(basename $(readlink -f $1)) | sed -r "s/^[^=]+=([^; ]+); [^=]+=([A-Za-z0-9]{8})[A-Za-z0-9]{32}; [^=]+=([^; ]+); [^=]+=\"(.+)\"; (.+)$/\1 \2 <\3> \4\n\5/g"
