#!/bin/bash

unset -v current_git_diff name category owner list_diff_log _list_diff_log
unset -f current_git_diff name category owner list_diff_log _list_diff_log

declare -xa current_git_diff=(
	"build"
	"cts"
	"customize/av/drm"
	"customize/base"
	"customize/framework_res/res"
	"customize/native"
	"customize/telephony"
	"frameworks/av"
	"frameworks/base"
	"frameworks/native"
	"hardware/libhardware"
	"hardware/qcom/gps"
	"system/core"
	"system/extras"
)

declare -xA name=(
	[AUD]="AUD Audio audio AudioFlinger Audioflinger audioflinger"
	[VID]="Codec Video video Streaming streaming Extractor extractor AAC Player player"
	[RIL]="RIL ril RADIO radio"
	[MM]="MM mediaserver DRM DLNA DTCP OMA"
	[WIFI]="WIFI wifi"
	[NET]="Network network wimax"
	[DISP]="ML DISP MediaLink surfaceflinger HWUI hwui hwcomposer renderer display Display"
	[POWR]="Power power BATT batt"
	[USB]="USB usb ADB adb"
	[CAM]="Camera CAM camera SlowMotion slowmotion Slowmotion"
	[GPS]="GPS gps"
	[BT]="BT Bluetooth bluetooth"
	[OTA]="FOTA OTA Recovery"
	[STRG]="fuse storage SD sdcard eMMC emmc EMMC mount"
	[SENR]="NFC Nfc nfc Sensor sensor LED led IrDA irda IRDA"
	[SCRT]="Security security encrypt Encrypt Decrypt decrypt cipher"
	[PERF]="Performance performance"
	[OTHR]=""
)

declare -xA category=(
	[AUD]="MM/Audio"
	[RIL]="RIL"
	[WIFI]="Wireless/Wifi"
	[NET]="Network"
	[DISP]="MM/Display"
	[POWR]="Power"
	[PERF]="Performance"
	[VID]="MM/Video"
	[USB]="USB"
	[CAM]="MM/Camera"
	[GPS]="Wireless/GPS"
	[BT]="Wireless/BT"
	[OTA]="FOTA"
	[STRG]="Storage"
	[SENR]="Sensors"
	[SCRT]="Security"
	[MM]="MM"
	[OTHR]="Other"
)

declare -xA owner=(
	[AUD]="Kiwi"
	[RIL]="Ivy"
	[WIFI]="Daniel"
	[NET]="Daniel"
	[DISP]="Chengyi"
	[POWR]="Steven"
	[PERF]="Adam"
	[VID]="Kiwi"
	[USB]="Steven"
	[CAM]="Daniel"
	[GPS]="Daniel"
	[BT]="Daniel"
	[OTA]="Daniel"
	[STRG]="Adam"
	[SENR]="Steven"
	[SCRT]="Daniel"
	[MM]="Kiwi"
	[OTHR]="Ivy"
)

list_diff_log ()
{
	declare _msg
	declare _cat
	declare _owner
	declare _rev

	if [[ $(git branch --list $1 $2 | wc -l) -eq 2 ]] && [[ "$(git log --format=%h $1..$2)" != "" ]]; then
		echo "=== $REPO_PATH ===";
		echo;
		echo '{| border=1 cellpadding=3 cellspacing=0';
		echo '|-';
		echo '! commit !! sumary !! author !! category !! owner !! status';
		_rev="$(git log $1..$2 --format=%h)";
		for i in $_rev; do
			_cat=""
			_owner=""
			_msg="$(git log $i -1 --format=%s)";
			for j in ${!name[@]}; do
				for k in ${name[$j]}; do
					if [[ "$(grep -m 1 -e $k <<< $_msg)" != "" ]]; then
						_cat="${category[$j]}";
						_owner="${owner[$j]}";
						break;
					fi
				done
				[[ "$_owner" != "" ]] && break;
			done
			git log $i -1 --format="|-%n| %h || %s || %ae || $_cat || $_owner ||";
		done
		echo "|}";
	fi
}

declare -x _list_diff_log;
declare -x _name;
declare -x _category;
declare -x _owner;

printf -v _list_diff_log 'eval %q' "$(declare -f list_diff_log)"
printf -v _name 'eval %q' "$(declare -p name)"
printf -v _category 'eval %q' "$(declare -p category)"
printf -v _owner 'eval %q' "$(declare -p owner)"

echo "== Monitoring projets =="
for i in ${current_git_diff[@]}; do
	echo "* $i"
done

echo "== New changes since $1 until $2 =="

repo forall ${current_git_diff[@]} -vc bash -c 'eval eval "$_name; $_category; $_owner; $_list_diff_log; list_diff_log $@"' $0 $@

echo "[[Category:SSD_Advance_Team5]]"
