#!/bin/bash
declare _path=/home/daniel/Desktop/logs/$(date +'%F')
mkdir -p $_path
sudo sed -i "s|\(LogFileName=\).\+$|\1$_path/$(date +'%H-%M_%S')$(test -n "$1" && echo _$1).log|g" /root/.config/CuteCom/CuteCom.conf
gksudo cutecom &

