#!/bin/bash
declare _script=/tmp/__$1.cutecom.exe__
declare _commandset="reboot_nvflash, reboot, battinfo, battcheck 0, logcat -c, logcat -v threadtime, writesku 1 020201ff, su, reboot bootloader, console"
declare _path=/home/daniel/Desktop/logs/$(date +'%F')
declare _file=$_path/$(date +'%H-%M_%S')$(test -n "$1" && echo _$1).log
cat <<EOF > $_script
#!/bin/bash
mkdir -p $_path

sed -ir "s|\(History=\).*$|\1$_commandset|g" /root/.config/CuteCom/CuteCom.conf && \\
sed -ir "s|\(LogFileName=\).*$|\1$_file|g" /root/.config/CuteCom/CuteCom.conf && \\
cutecom && \\
chown -R daniel:daniel $_path && \\
(test -s $_file || rm -f $_file)

rm -dv $_path
EOF

chmod 700 $_script && \
gksudo $_script &

