#!/bin/bash

test "$1" != "daniel_tsai" && (
	git config --global user.name "Replicator";
	git config --global user.email "replicator@htc.com";
) || (
	git config --global user.name "Daniel Tsai";
	git config --global user.email "daniel_tsai@htc.com";
)
