#!/bin/bash
smb_exe()
{
	_smb_client='smbclient -U NVsign \\10.8.9.172\signednv HTCsignNV'
	echo -e "$*" | $_smb_client
}

_user="$1"
_gpg="$2"
_put_list="mts_prod mts_preboot_prod rawbct.img        hboot.img        nvtboot.img        nvtbootwb0.bin        tos.img        $_gpg"
_get_list="mts_prod mts_preboot_prod rawbct_signed.bct hboot_signed.img nvtboot_signed.img nvtbootwb0_signed.bin tos.img blob.bin.gpg"

if smb_exe "posix\nls $_user" | grep NT_STATUS_NO_SUCH_FILE; then
	_cmd=$(cat <<-EOF
		posix\n
		prompt\n
		md $_user\n
		cd $_user\n
		lcd ../unsigned\n
		mput $_put_list\n
		lcd ../signed\n
		mput enabled_t1\n
		EOF
	)
	_signed=0

	smb_exe "$_cmd"
	for((i=1; i<=20; ++i)); do
		echo "... Waiting for signing ..."
		sleep 5s
		if smb_exe "posix\ncd $_user\nls hboot.img" | grep NT_STATUS_NO_SUCH_FILE; then
			echo "... Done ..."
			sleep 2s
			_signed=1
			break;
		fi
	done
	if [[ $_signed -eq 1 ]]; then
		_cmd=$(cat <<-EOF
			posix\n
			prompt\n
			cd $_user\n
			mget $_get_list\n
			rm *\n
			cd ../\n
			rd $_user\n
			EOF
		)
		smb_exe "$_cmd"
		md5sum $_get_list | sed -r "s/_signed//g" | tee info.txt
		. ./rename
	else
		echo "Sign images timeout"
	fi
else
	echo "Sign server is using by someone, now..."
fi
