#!/bin/bash
smb_exe()
{
	_smb_client='smbclient -U NVsign \\10.8.9.172\signednv HTCsignNV'
	echo -e "$*" | $_smb_client
}

if smb_exe "posix\nls hboot*" | grep NT_STATUS_NO_SUCH_FILE; then
	smb_exe "posix\nlcd ../unsigned\nput mts_prod\nput mts_preboot_prod\nput rawbct.img\nput hboot.img\nput nvtboot.img\nput nvtbootwb0.bin\nput tos.img"
	smb_exe "rename README.txt enabled_t1"
	_signed=0
	for((i=1; i<=20; ++i)); do
		echo "... Waiting for signing ..."
		sleep 5s
		if smb_exe "posix\nls hboot.img" | grep NT_STATUS_NO_SUCH_FILE; then
			echo "... Done ..."
			sleep 2s
			_signed=1
			break;
		fi
	done
	if [[ $_signed -eq 1 ]]; then
		smb_exe "posix\nget mts_prod\nget mts_preboot_prod\nget rawbct_signed.bct\nget hboot_signed.img\nget nvtboot_signed.img\nget nvtbootwb0_signed.bin\nget tos_signed.img\nget blob.bin.gpg"
		smb_exe "posix\nrm mts_prod\nrm mts_preboot_prod\nrm rawbct_signed.bct\nrm hboot_signed.img\nrm nvtboot_signed.img\nrm nvtbootwb0_signed.bin\nrm tos_signed.img\nrm blob.bin.gpg"
		. ./rename
		md5sum hboot.img mts_prod mts_preboot_prod rawbct.img nvtboot.img nvtbootwb0.bin tos.img blob.bin.gpg | tee info.txt
	else
		echo "Sign images timeout"
	fi
else
	echo "Sign server is using by someone, now..."
fi
